// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ovjdXhydzXTq3Bc7u9wCpt
// Component: _Zq7sjOf7bc
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import DashboardSidebar from "../../DashboardSidebar"; // plasmic-import: 7WJwRnVAxlX/component
import BusinessHeader from "../../BusinessHeader"; // plasmic-import: QNsWw2e-3G/component
import MessagesBox from "../../MessagesBox"; // plasmic-import: 5K0H0lW6HF/component
import InventoryList from "../../InventoryList"; // plasmic-import: Gn6XkLaEoG/component
import { useScreenVariants as useScreenVariantsgcBBykOvh4Vq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gcB_bykOvh4VQ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_2_geda.module.css"; // plasmic-import: ovjdXhydzXTq3Bc7u9wCpt/projectcss
import sty from "./PlasmicManageBusiness.module.css"; // plasmic-import: _Zq7sjOf7bc/css
import Star6Icon from "./icons/PlasmicIcon__Star6"; // plasmic-import: W5VMX--tmZ/icon
import Star7Icon from "./icons/PlasmicIcon__Star7"; // plasmic-import: SV_e28LHM/icon
import Star8Icon from "./icons/PlasmicIcon__Star8"; // plasmic-import: -AXYjo2d_S/icon
import Star9Icon from "./icons/PlasmicIcon__Star9"; // plasmic-import: 20LYPBw4Ub/icon
import Star10Icon from "./icons/PlasmicIcon__Star10"; // plasmic-import: IthMtVSlY9/icon

export const PlasmicManageBusiness__VariantProps = new Array();

export const PlasmicManageBusiness__ArgProps = new Array();

function PlasmicManageBusiness__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgcBBykOvh4Vq()
  });

  return (
    <React.Fragment>
      <div
        data-plasmic-name={"root2"}
        data-plasmic-override={overrides.root2}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root2
        )}
      >
        <DashboardSidebar
          data-plasmic-name={"dashboardSidebar"}
          data-plasmic-override={overrides.dashboardSidebar}
          className={classNames("__wab_instance", sty.dashboardSidebar)}
        />

        <div
          data-plasmic-name={"main"}
          data-plasmic-override={overrides.main}
          className={classNames(projectcss.all, sty.main)}
        >
          <BusinessHeader
            data-plasmic-name={"businessHeader"}
            data-plasmic-override={overrides.businessHeader}
            className={classNames("__wab_instance", sty.businessHeader)}
          />

          <div
            data-plasmic-name={"peopleMainContent"}
            data-plasmic-override={overrides.peopleMainContent}
            className={classNames(projectcss.all, sty.peopleMainContent)}
          >
            <div
              data-plasmic-name={"peopleMainContentLeft"}
              data-plasmic-override={overrides.peopleMainContentLeft}
              className={classNames(projectcss.all, sty.peopleMainContentLeft)}
            >
              <div
                data-plasmic-name={"rectangle209"}
                data-plasmic-override={overrides.rectangle209}
                className={classNames(projectcss.all, sty.rectangle209)}
              >
                <span
                  data-plasmic-name={"span"}
                  data-plasmic-override={overrides.span}
                  className={classNames(
                    projectcss.all,
                    projectcss.span,
                    projectcss.__wab_text,
                    sty.span
                  )}
                >
                  {"People"}
                </span>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qU5
                  )}
                >
                  {"Manage Businessess"}
                </div>

                <div
                  data-plasmic-name={"group223"}
                  data-plasmic-override={overrides.group223}
                  className={classNames(projectcss.all, sty.group223)}
                >
                  <div
                    data-plasmic-name={"group222"}
                    data-plasmic-override={overrides.group222}
                    className={classNames(projectcss.all, sty.group222)}
                  >
                    <div
                      data-plasmic-name={"rectangle267"}
                      data-plasmic-override={overrides.rectangle267}
                      className={classNames(projectcss.all, sty.rectangle267)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mbK5Q
                      )}
                    >
                      {"+"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cSbnJ
                    )}
                  >
                    {"Add a new Business page"}
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle218"}
                data-plasmic-override={overrides.rectangle218}
                className={classNames(projectcss.all, sty.rectangle218)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gYkV8
                  )}
                >
                  {"Your Business Pages"}
                </div>

                <div
                  data-plasmic-name={"busnesses"}
                  data-plasmic-override={overrides.busnesses}
                  className={classNames(projectcss.all, sty.busnesses)}
                >
                  <div
                    data-plasmic-name={"group307"}
                    data-plasmic-override={overrides.group307}
                    className={classNames(projectcss.all, sty.group307)}
                  >
                    <div
                      data-plasmic-name={"rectangle264"}
                      data-plasmic-override={overrides.rectangle264}
                      className={classNames(projectcss.all, sty.rectangle264)}
                    />

                    <div
                      data-plasmic-name={"group305"}
                      data-plasmic-override={overrides.group305}
                      className={classNames(projectcss.all, sty.group305)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fScby
                        )}
                      >
                        {"Business Page 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kgUrl
                        )}
                      >
                        {"Lagos | Nigeria"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sd7Ee
                        )}
                      >
                        {"Estd. 2011"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kSxd3
                        )}
                      >
                        {"Average rating : 4.5"}
                      </div>

                      <div
                        data-plasmic-name={"group224"}
                        data-plasmic-override={overrides.group224}
                        className={classNames(projectcss.all, sty.group224)}
                      >
                        <Star6Icon
                          className={classNames(projectcss.all, sty.svg__xbQRm)}
                          role={"img"}
                        />

                        <Star7Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___8Od49
                          )}
                          role={"img"}
                        />

                        <Star8Icon
                          className={classNames(projectcss.all, sty.svg__o3DNp)}
                          role={"img"}
                        />

                        <Star9Icon
                          className={classNames(projectcss.all, sty.svg__echCg)}
                          role={"img"}
                        />

                        <Star10Icon
                          className={classNames(projectcss.all, sty.svg__jEn27)}
                          role={"img"}
                        />
                      </div>

                      <div
                        data-plasmic-name={"rectangle307"}
                        data-plasmic-override={overrides.rectangle307}
                        className={classNames(projectcss.all, sty.rectangle307)}
                      />
                    </div>
                  </div>

                  <button
                    data-plasmic-name={"group225"}
                    data-plasmic-override={overrides.group225}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty.group225
                    )}
                  >
                    <div
                      data-plasmic-name={"rectangle268"}
                      data-plasmic-override={overrides.rectangle268}
                      className={classNames(projectcss.all, sty.rectangle268)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9INgG
                      )}
                    >
                      {"View page"}
                    </div>
                  </button>
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle219"}
                data-plasmic-override={overrides.rectangle219}
                className={classNames(projectcss.all, sty.rectangle219)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vkNfq
                  )}
                >
                  {"Suggested Business Pages"}
                </div>

                <div
                  data-plasmic-name={"busnesses2"}
                  data-plasmic-override={overrides.busnesses2}
                  className={classNames(projectcss.all, sty.busnesses2)}
                >
                  <div
                    data-plasmic-name={"group308"}
                    data-plasmic-override={overrides.group308}
                    className={classNames(projectcss.all, sty.group308)}
                  >
                    <div
                      data-plasmic-name={"rectangle265"}
                      data-plasmic-override={overrides.rectangle265}
                      className={classNames(projectcss.all, sty.rectangle265)}
                    />

                    <div
                      data-plasmic-name={"group306"}
                      data-plasmic-override={overrides.group306}
                      className={classNames(projectcss.all, sty.group306)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vWagX
                        )}
                      >
                        {"Business Page 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qfcRj
                        )}
                      >
                        {"Lagos | Nigeria"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r6RyF
                        )}
                      >
                        {"Estd. 2011"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5Sy6C
                        )}
                      >
                        {"Average rating : 4.5"}
                      </div>

                      <div
                        data-plasmic-name={"group226"}
                        data-plasmic-override={overrides.group226}
                        className={classNames(projectcss.all, sty.group226)}
                      >
                        <Star6Icon
                          className={classNames(projectcss.all, sty.svg__x1Mpv)}
                          role={"img"}
                        />

                        <Star7Icon
                          className={classNames(projectcss.all, sty.svg__pvC2P)}
                          role={"img"}
                        />

                        <Star8Icon
                          className={classNames(projectcss.all, sty.svg__bqqkL)}
                          role={"img"}
                        />

                        <Star9Icon
                          className={classNames(projectcss.all, sty.svg__jFdwD)}
                          role={"img"}
                        />

                        <Star10Icon
                          className={classNames(projectcss.all, sty.svg__iPHwK)}
                          role={"img"}
                        />
                      </div>

                      <div
                        data-plasmic-name={"rectangle308"}
                        data-plasmic-override={overrides.rectangle308}
                        className={classNames(projectcss.all, sty.rectangle308)}
                      />
                    </div>
                  </div>

                  <button
                    data-plasmic-name={"group227"}
                    data-plasmic-override={overrides.group227}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty.group227
                    )}
                  >
                    <div
                      data-plasmic-name={"rectangle269"}
                      data-plasmic-override={overrides.rectangle269}
                      className={classNames(projectcss.all, sty.rectangle269)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gyysm
                      )}
                    >
                      {"View page"}
                    </div>
                  </button>
                </div>
              </div>
            </div>

            {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
              <div
                data-plasmic-name={"peopleMainContentRight"}
                data-plasmic-override={overrides.peopleMainContentRight}
                className={classNames(
                  projectcss.all,
                  sty.peopleMainContentRight
                )}
              >
                <MessagesBox
                  data-plasmic-name={"messagesBox"}
                  data-plasmic-override={overrides.messagesBox}
                  className={classNames("__wab_instance", sty.messagesBox)}
                />

                <InventoryList
                  data-plasmic-name={"inventoryList"}
                  data-plasmic-override={overrides.inventoryList}
                  className={classNames("__wab_instance", sty.inventoryList)}
                />
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root2: [
    "root2",
    "dashboardSidebar",
    "main",
    "businessHeader",
    "peopleMainContent",
    "peopleMainContentLeft",
    "rectangle209",
    "span",
    "group223",
    "group222",
    "rectangle267",
    "rectangle218",
    "busnesses",
    "group307",
    "rectangle264",
    "group305",
    "group224",
    "rectangle307",
    "group225",
    "rectangle268",
    "rectangle219",
    "busnesses2",
    "group308",
    "rectangle265",
    "group306",
    "group226",
    "rectangle308",
    "group227",
    "rectangle269",
    "peopleMainContentRight",
    "messagesBox",
    "inventoryList"
  ],

  dashboardSidebar: ["dashboardSidebar"],
  main: [
    "main",
    "businessHeader",
    "peopleMainContent",
    "peopleMainContentLeft",
    "rectangle209",
    "span",
    "group223",
    "group222",
    "rectangle267",
    "rectangle218",
    "busnesses",
    "group307",
    "rectangle264",
    "group305",
    "group224",
    "rectangle307",
    "group225",
    "rectangle268",
    "rectangle219",
    "busnesses2",
    "group308",
    "rectangle265",
    "group306",
    "group226",
    "rectangle308",
    "group227",
    "rectangle269",
    "peopleMainContentRight",
    "messagesBox",
    "inventoryList"
  ],

  businessHeader: ["businessHeader"],
  peopleMainContent: [
    "peopleMainContent",
    "peopleMainContentLeft",
    "rectangle209",
    "span",
    "group223",
    "group222",
    "rectangle267",
    "rectangle218",
    "busnesses",
    "group307",
    "rectangle264",
    "group305",
    "group224",
    "rectangle307",
    "group225",
    "rectangle268",
    "rectangle219",
    "busnesses2",
    "group308",
    "rectangle265",
    "group306",
    "group226",
    "rectangle308",
    "group227",
    "rectangle269",
    "peopleMainContentRight",
    "messagesBox",
    "inventoryList"
  ],

  peopleMainContentLeft: [
    "peopleMainContentLeft",
    "rectangle209",
    "span",
    "group223",
    "group222",
    "rectangle267",
    "rectangle218",
    "busnesses",
    "group307",
    "rectangle264",
    "group305",
    "group224",
    "rectangle307",
    "group225",
    "rectangle268",
    "rectangle219",
    "busnesses2",
    "group308",
    "rectangle265",
    "group306",
    "group226",
    "rectangle308",
    "group227",
    "rectangle269"
  ],

  rectangle209: [
    "rectangle209",
    "span",
    "group223",
    "group222",
    "rectangle267"
  ],

  span: ["span"],
  group223: ["group223", "group222", "rectangle267"],
  group222: ["group222", "rectangle267"],
  rectangle267: ["rectangle267"],
  rectangle218: [
    "rectangle218",
    "busnesses",
    "group307",
    "rectangle264",
    "group305",
    "group224",
    "rectangle307",
    "group225",
    "rectangle268"
  ],

  busnesses: [
    "busnesses",
    "group307",
    "rectangle264",
    "group305",
    "group224",
    "rectangle307",
    "group225",
    "rectangle268"
  ],

  group307: [
    "group307",
    "rectangle264",
    "group305",
    "group224",
    "rectangle307"
  ],

  rectangle264: ["rectangle264"],
  group305: ["group305", "group224", "rectangle307"],
  group224: ["group224"],
  rectangle307: ["rectangle307"],
  group225: ["group225", "rectangle268"],
  rectangle268: ["rectangle268"],
  rectangle219: [
    "rectangle219",
    "busnesses2",
    "group308",
    "rectangle265",
    "group306",
    "group226",
    "rectangle308",
    "group227",
    "rectangle269"
  ],

  busnesses2: [
    "busnesses2",
    "group308",
    "rectangle265",
    "group306",
    "group226",
    "rectangle308",
    "group227",
    "rectangle269"
  ],

  group308: [
    "group308",
    "rectangle265",
    "group306",
    "group226",
    "rectangle308"
  ],

  rectangle265: ["rectangle265"],
  group306: ["group306", "group226", "rectangle308"],
  group226: ["group226"],
  rectangle308: ["rectangle308"],
  group227: ["group227", "rectangle269"],
  rectangle269: ["rectangle269"],
  peopleMainContentRight: [
    "peopleMainContentRight",
    "messagesBox",
    "inventoryList"
  ],

  messagesBox: ["messagesBox"],
  inventoryList: ["inventoryList"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicManageBusiness__ArgProps,
          internalVariantPropNames: PlasmicManageBusiness__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicManageBusiness__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root2") {
    func.displayName = "PlasmicManageBusiness";
  } else {
    func.displayName = `PlasmicManageBusiness.${nodeName}`;
  }
  return func;
}

export const PlasmicManageBusiness = Object.assign(
  // Top-level PlasmicManageBusiness renders the root element
  makeNodeComponent("root2"),
  {
    // Helper components rendering sub-elements
    dashboardSidebar: makeNodeComponent("dashboardSidebar"),
    main: makeNodeComponent("main"),
    businessHeader: makeNodeComponent("businessHeader"),
    peopleMainContent: makeNodeComponent("peopleMainContent"),
    peopleMainContentLeft: makeNodeComponent("peopleMainContentLeft"),
    rectangle209: makeNodeComponent("rectangle209"),
    span: makeNodeComponent("span"),
    group223: makeNodeComponent("group223"),
    group222: makeNodeComponent("group222"),
    rectangle267: makeNodeComponent("rectangle267"),
    rectangle218: makeNodeComponent("rectangle218"),
    busnesses: makeNodeComponent("busnesses"),
    group307: makeNodeComponent("group307"),
    rectangle264: makeNodeComponent("rectangle264"),
    group305: makeNodeComponent("group305"),
    group224: makeNodeComponent("group224"),
    rectangle307: makeNodeComponent("rectangle307"),
    group225: makeNodeComponent("group225"),
    rectangle268: makeNodeComponent("rectangle268"),
    rectangle219: makeNodeComponent("rectangle219"),
    busnesses2: makeNodeComponent("busnesses2"),
    group308: makeNodeComponent("group308"),
    rectangle265: makeNodeComponent("rectangle265"),
    group306: makeNodeComponent("group306"),
    group226: makeNodeComponent("group226"),
    rectangle308: makeNodeComponent("rectangle308"),
    group227: makeNodeComponent("group227"),
    rectangle269: makeNodeComponent("rectangle269"),
    peopleMainContentRight: makeNodeComponent("peopleMainContentRight"),
    messagesBox: makeNodeComponent("messagesBox"),
    inventoryList: makeNodeComponent("inventoryList"),
    // Metadata about props expected for PlasmicManageBusiness
    internalVariantProps: PlasmicManageBusiness__VariantProps,
    internalArgProps: PlasmicManageBusiness__ArgProps
  }
);

export default PlasmicManageBusiness;
/* prettier-ignore-end */
