// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ovjdXhydzXTq3Bc7u9wCpt
// Component: 05xKepNiDk
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsgcBBykOvh4Vq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gcB_bykOvh4VQ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_2_geda.module.css"; // plasmic-import: ovjdXhydzXTq3Bc7u9wCpt/projectcss
import sty from "./PlasmicBusiness.module.css"; // plasmic-import: 05xKepNiDk/css
import SignOutIcon from "./icons/PlasmicIcon__SignOut"; // plasmic-import: PV-wOd8DPw/icon
import HouseIcon from "./icons/PlasmicIcon__House"; // plasmic-import: IdSuw-EtCN/icon
import UserCircleIcon from "./icons/PlasmicIcon__UserCircle"; // plasmic-import: EP5zGWwJ1X/icon
import Vector96Icon from "./icons/PlasmicIcon__Vector96"; // plasmic-import: 9n_rLIVux/icon
import Vector97Icon from "./icons/PlasmicIcon__Vector97"; // plasmic-import: Rb7mIprIrQ/icon
import BellIcon from "./icons/PlasmicIcon__Bell"; // plasmic-import: grfZD_Hnz9/icon
import MagnifyingGlassIcon from "./icons/PlasmicIcon__MagnifyingGlass"; // plasmic-import: vPllSbWx1H/icon
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: sFbk0B4_vB/icon
import Star2Icon from "./icons/PlasmicIcon__Star2"; // plasmic-import: w5JllfIkrJ/icon
import Star3Icon from "./icons/PlasmicIcon__Star3"; // plasmic-import: Yl4IrwGzJU/icon
import Star4Icon from "./icons/PlasmicIcon__Star4"; // plasmic-import: XQCQaCpB-/icon
import Star5Icon from "./icons/PlasmicIcon__Star5"; // plasmic-import: 287U2hOue7/icon
import storefrontXeuODvyCe from "./images/storefront.svg"; // plasmic-import: xeuODvy_ce/picture
import unsplash5N3Jp9WajTsYDdWxVaitl from "./images/unsplash5N3Jp9WajTs.svg"; // plasmic-import: yDDWxVaitl/picture
import unsplashINwSiOcNzMgEGqqCl3UoC2 from "./images/unsplashINwSiOcNzMg.jpeg"; // plasmic-import: EGqqCl3UoC2/picture

export const PlasmicBusiness__VariantProps = new Array();

export const PlasmicBusiness__ArgProps = new Array();

function PlasmicBusiness__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgcBBykOvh4Vq()
  });

  return (
    <React.Fragment>
      <div
        data-plasmic-name={"business"}
        data-plasmic-override={overrides.business}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.business
        )}
      >
        {(hasVariant(globalVariants, "screen", "tablet") ? true : true) ? (
          <div
            data-plasmic-name={"sidebar"}
            data-plasmic-override={overrides.sidebar}
            className={classNames(projectcss.all, sty.sidebar)}
          >
            {(hasVariant(globalVariants, "screen", "tablet") ? true : true) ? (
              <div
                data-plasmic-name={"group246"}
                data-plasmic-override={overrides.group246}
                className={classNames(projectcss.all, sty.group246)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"group214"}
                    data-plasmic-override={overrides.group214}
                    className={classNames(projectcss.all, sty.group214)}
                  >
                    <SignOutIcon
                      className={classNames(projectcss.all, sty.svg__jz15W)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cCpyq
                      )}
                    >
                      {"Sign out"}
                    </div>
                  </div>
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "tablet") ? true : true
                ) ? (
                  <div
                    data-plasmic-name={"group244"}
                    data-plasmic-override={overrides.group244}
                    className={classNames(projectcss.all, sty.group244)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"group140"}
                      data-plasmic-override={overrides.group140}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.group140)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"home"}
                        data-plasmic-override={overrides.home}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.home)}
                      >
                        <HouseIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___4Ki1V
                          )}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qq74
                          )}
                        >
                          {"Home"}
                        </div>
                      </p.Stack>

                      <div
                        data-plasmic-name={"marketplace"}
                        data-plasmic-override={overrides.marketplace}
                        className={classNames(projectcss.all, sty.marketplace)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ouIbj)}
                          displayHeight={"32px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: storefrontXeuODvyCe,
                            fullWidth: 32,
                            fullHeight: 32,
                            aspectRatio: 1
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kq5Wo
                          )}
                        >
                          {"Business"}
                        </div>
                      </div>

                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"profile"}
                        data-plasmic-override={overrides.profile}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.profile)}
                      >
                        <UserCircleIcon
                          className={classNames(projectcss.all, sty.svg__rm0V0)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lsGhg
                          )}
                        >
                          {"People"}
                        </div>
                      </p.Stack>

                      <div
                        data-plasmic-name={"messages"}
                        data-plasmic-override={overrides.messages}
                        className={classNames(projectcss.all, sty.messages)}
                      >
                        <div
                          data-plasmic-name={"messages2"}
                          data-plasmic-override={overrides.messages2}
                          className={classNames(projectcss.all, sty.messages2)}
                        >
                          <Vector96Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__osIM
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bhRhI
                            )}
                          >
                            {"Messages"}
                          </div>
                        </div>

                        <Vector97Icon
                          className={classNames(projectcss.all, sty.svg__sBeZu)}
                          role={"img"}
                        />

                        <Vector97Icon
                          className={classNames(projectcss.all, sty.svg__pcrhb)}
                          role={"img"}
                        />

                        <Vector97Icon
                          className={classNames(projectcss.all, sty.svg__nCupZ)}
                          role={"img"}
                        />
                      </div>

                      <div
                        data-plasmic-name={"nofitication"}
                        data-plasmic-override={overrides.nofitication}
                        className={classNames(projectcss.all, sty.nofitication)}
                      >
                        <BellIcon
                          className={classNames(projectcss.all, sty.svg__oaYsY)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6DNk2
                          )}
                        >
                          {"Notification"}
                        </div>
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"group245"}
                      data-plasmic-override={overrides.group245}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.group245)}
                    >
                      <SignOutIcon
                        className={classNames(projectcss.all, sty.svg__vObgZ)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jyFUu
                        )}
                      >
                        {"Sign out"}
                      </div>
                    </p.Stack>
                  </div>
                ) : null}
              </div>
            ) : null}
          </div>
        ) : null}

        <div
          data-plasmic-name={"main"}
          data-plasmic-override={overrides.main}
          className={classNames(projectcss.all, sty.main)}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <div
              data-plasmic-name={"group243"}
              data-plasmic-override={overrides.group243}
              className={classNames(projectcss.all, sty.group243)}
            >
              <div
                data-plasmic-name={"_2Geda11"}
                data-plasmic-override={overrides._2Geda11}
                className={classNames(projectcss.all, sty._2Geda11)}
              />

              <div
                data-plasmic-name={"group10"}
                data-plasmic-override={overrides.group10}
                className={classNames(projectcss.all, sty.group10)}
              >
                <div
                  data-plasmic-name={"group241"}
                  data-plasmic-override={overrides.group241}
                  className={classNames(projectcss.all, sty.group241)}
                >
                  <input
                    data-plasmic-name={"rectangle30"}
                    data-plasmic-override={overrides.rectangle30}
                    className={classNames(
                      projectcss.all,
                      projectcss.input,
                      sty.rectangle30
                    )}
                    placeholder={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "search"
                        : "search name, place and business"
                    }
                    type={"text"}
                  />

                  <MagnifyingGlassIcon
                    className={classNames(projectcss.all, sty.svg__p21AX)}
                    role={"img"}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"group242"}
                data-plasmic-override={overrides.group242}
                className={classNames(projectcss.all, sty.group242)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dr9K6)}
                  displayHeight={"40px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"40px"}
                  loading={"lazy"}
                  src={{
                    src: unsplash5N3Jp9WajTsYDdWxVaitl,
                    fullWidth: 40,
                    fullHeight: 40,
                    aspectRatio: 1
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lkVps
                  )}
                >
                  {"My Profile"}
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"content"}
            data-plasmic-override={overrides.content}
            className={classNames(projectcss.all, sty.content)}
          >
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <div
                data-plasmic-name={"outletTop"}
                data-plasmic-override={overrides.outletTop}
                className={classNames(projectcss.all, sty.outletTop)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__klm3R
                  )}
                >
                  {"Buy and sell instantly"}
                </div>

                <div
                  data-plasmic-name={"group289"}
                  data-plasmic-override={overrides.group289}
                  className={classNames(projectcss.all, sty.group289)}
                >
                  <button
                    data-plasmic-name={"rectangle296"}
                    data-plasmic-override={overrides.rectangle296}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty.rectangle296
                    )}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__geHup
                    )}
                  >
                    {"Manage Businesess"}
                  </div>
                </div>
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"rectangle218"}
                data-plasmic-override={overrides.rectangle218}
                hasGap={true}
                className={classNames(projectcss.all, sty.rectangle218)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iGiig
                  )}
                >
                  {"Trending and Hot"}
                </div>

                <div
                  data-plasmic-name={"group161"}
                  data-plasmic-override={overrides.group161}
                  className={classNames(projectcss.all, sty.group161)}
                >
                  {true ? (
                    <div
                      data-plasmic-name={"group160"}
                      data-plasmic-override={overrides.group160}
                      className={classNames(projectcss.all, sty.group160)}
                    >
                      <div
                        data-plasmic-name={"rectangle216"}
                        data-plasmic-override={overrides.rectangle216}
                        className={classNames(projectcss.all, sty.rectangle216)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__t687R)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: unsplashINwSiOcNzMgEGqqCl3UoC2,
                            fullWidth: 2880,
                            fullHeight: 1620,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__trRYs
                        )}
                      >
                        {"Semi detached duplex"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aFgPq
                        )}
                      >
                        {"#200,000"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a9Vd9
                        )}
                      >
                        {"Lekki, Lagos"}
                      </div>
                    </div>
                  ) : null}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"rectangle213"}
                data-plasmic-override={overrides.rectangle213}
                className={classNames(projectcss.all, sty.rectangle213)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cRdrn
                  )}
                >
                  {"Suggested Businesses"}
                </div>

                <div
                  data-plasmic-name={"group162"}
                  data-plasmic-override={overrides.group162}
                  className={classNames(projectcss.all, sty.group162)}
                >
                  <div
                    data-plasmic-name={"group230"}
                    data-plasmic-override={overrides.group230}
                    className={classNames(projectcss.all, sty.group230)}
                  >
                    <div
                      data-plasmic-name={"rectangle264"}
                      data-plasmic-override={overrides.rectangle264}
                      className={classNames(projectcss.all, sty.rectangle264)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___0FitV)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: unsplashINwSiOcNzMgEGqqCl3UoC2,
                          fullWidth: 2880,
                          fullHeight: 1620,
                          aspectRatio: undefined
                        }}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group286"}
                      data-plasmic-override={overrides.group286}
                      className={classNames(projectcss.all, sty.group286)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mkeef
                        )}
                      >
                        {"Business Page 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uu46
                        )}
                      >
                        {"Lagos | Nigeria"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__c9Wek
                        )}
                      >
                        {"Estd. 2011"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yMpjc
                        )}
                      >
                        {"Average rating : 4.5"}
                      </div>

                      <div
                        data-plasmic-name={"group224"}
                        data-plasmic-override={overrides.group224}
                        className={classNames(projectcss.all, sty.group224)}
                      >
                        <StarIcon
                          className={classNames(projectcss.all, sty.svg__qK0KP)}
                          role={"img"}
                        />

                        <Star2Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___2B220
                          )}
                          role={"img"}
                        />

                        <Star3Icon
                          className={classNames(projectcss.all, sty.svg__pszMx)}
                          role={"img"}
                        />

                        <Star4Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3Dg7D
                          )}
                          role={"img"}
                        />

                        <Star5Icon
                          className={classNames(projectcss.all, sty.svg__bGy96)}
                          role={"img"}
                        />
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"group225"}
                      data-plasmic-override={overrides.group225}
                      className={classNames(projectcss.all, sty.group225)}
                    >
                      <button
                        data-plasmic-name={"rectangle268"}
                        data-plasmic-override={overrides.rectangle268}
                        className={classNames(
                          projectcss.all,
                          projectcss.button,
                          sty.rectangle268
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iuPi2
                        )}
                      >
                        {"Follow"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle214"}
                data-plasmic-override={overrides.rectangle214}
                className={classNames(projectcss.all, sty.rectangle214)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6PDlT
                  )}
                >
                  {"Automobile"}
                </div>

                <div
                  data-plasmic-name={"group164"}
                  data-plasmic-override={overrides.group164}
                  className={classNames(projectcss.all, sty.group164)}
                >
                  {true ? (
                    <div
                      data-plasmic-name={"group165"}
                      data-plasmic-override={overrides.group165}
                      className={classNames(projectcss.all, sty.group165)}
                    >
                      <div
                        data-plasmic-name={"rectangle219"}
                        data-plasmic-override={overrides.rectangle219}
                        className={classNames(projectcss.all, sty.rectangle219)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ri9Vw)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: unsplashINwSiOcNzMgEGqqCl3UoC2,
                            fullWidth: 2880,
                            fullHeight: 1620,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nUMe7
                        )}
                      >
                        {"Semi detached duplex"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jEfa0
                        )}
                      >
                        {"#200,000"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lI5J6
                        )}
                      >
                        {"Lekki, Lagos"}
                      </div>
                    </div>
                  ) : null}
                </div>
              </div>
            </div>

            {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
              <div
                data-plasmic-name={"widget"}
                data-plasmic-override={overrides.widget}
                className={classNames(projectcss.all, sty.widget)}
              >
                <div
                  data-plasmic-name={"categoriesBox"}
                  data-plasmic-override={overrides.categoriesBox}
                  className={classNames(projectcss.all, sty.categoriesBox)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1stUp
                    )}
                  >
                    {"Select Category"}
                  </div>

                  <div
                    data-plasmic-name={"categoriesGrid"}
                    data-plasmic-override={overrides.categoriesGrid}
                    className={classNames(projectcss.all, sty.categoriesGrid)}
                  >
                    <div
                      data-plasmic-name={"group116"}
                      data-plasmic-override={overrides.group116}
                      className={classNames(projectcss.all, sty.group116)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__bPCvX)}
                        displayHeight={"38px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"38px"}
                        loading={"lazy"}
                        src={{
                          src: unsplashINwSiOcNzMgEGqqCl3UoC2,
                          fullWidth: 2880,
                          fullHeight: 1620,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__m5YuW
                        )}
                      >
                        {"Phones &\nDevices"}
                      </div>
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"inventoryList"}
                  data-plasmic-override={overrides.inventoryList}
                  className={classNames(projectcss.all, sty.inventoryList)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__megKa
                    )}
                  >
                    {"My Inventory"}
                  </div>

                  <div
                    data-plasmic-name={"list"}
                    data-plasmic-override={overrides.list}
                    className={classNames(projectcss.all, sty.list)}
                  >
                    <div
                      data-plasmic-name={"group166"}
                      data-plasmic-override={overrides.group166}
                      className={classNames(projectcss.all, sty.group166)}
                    >
                      <div
                        data-plasmic-name={"redNike"}
                        data-plasmic-override={overrides.redNike}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.redNike
                        )}
                      >
                        {"Red Nike "}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vtDit
                        )}
                      >
                        {"#2,000,000"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vetqv
                        )}
                      >
                        {"Posted 24/02/2022"}
                      </div>

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___4HKfg)}
                        displayHeight={"58px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"58px"}
                        loading={"lazy"}
                        src={{
                          src: unsplashINwSiOcNzMgEGqqCl3UoC2,
                          fullWidth: 2880,
                          fullHeight: 1620,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  business: [
    "business",
    "sidebar",
    "group246",
    "group214",
    "group244",
    "group140",
    "home",
    "marketplace",
    "profile",
    "messages",
    "messages2",
    "nofitication",
    "group245",
    "main",
    "header",
    "group243",
    "_2Geda11",
    "group10",
    "group241",
    "rectangle30",
    "group242",
    "content",
    "freeBox",
    "outletTop",
    "group289",
    "rectangle296",
    "rectangle218",
    "group161",
    "group160",
    "rectangle216",
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268",
    "rectangle214",
    "group164",
    "group165",
    "rectangle219",
    "widget",
    "categoriesBox",
    "categoriesGrid",
    "group116",
    "inventoryList",
    "list",
    "group166",
    "redNike"
  ],

  sidebar: [
    "sidebar",
    "group246",
    "group214",
    "group244",
    "group140",
    "home",
    "marketplace",
    "profile",
    "messages",
    "messages2",
    "nofitication",
    "group245"
  ],

  group246: [
    "group246",
    "group214",
    "group244",
    "group140",
    "home",
    "marketplace",
    "profile",
    "messages",
    "messages2",
    "nofitication",
    "group245"
  ],

  group214: ["group214"],
  group244: [
    "group244",
    "group140",
    "home",
    "marketplace",
    "profile",
    "messages",
    "messages2",
    "nofitication",
    "group245"
  ],

  group140: [
    "group140",
    "home",
    "marketplace",
    "profile",
    "messages",
    "messages2",
    "nofitication"
  ],

  home: ["home"],
  marketplace: ["marketplace"],
  profile: ["profile"],
  messages: ["messages", "messages2"],
  messages2: ["messages2"],
  nofitication: ["nofitication"],
  group245: ["group245"],
  main: [
    "main",
    "header",
    "group243",
    "_2Geda11",
    "group10",
    "group241",
    "rectangle30",
    "group242",
    "content",
    "freeBox",
    "outletTop",
    "group289",
    "rectangle296",
    "rectangle218",
    "group161",
    "group160",
    "rectangle216",
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268",
    "rectangle214",
    "group164",
    "group165",
    "rectangle219",
    "widget",
    "categoriesBox",
    "categoriesGrid",
    "group116",
    "inventoryList",
    "list",
    "group166",
    "redNike"
  ],

  header: [
    "header",
    "group243",
    "_2Geda11",
    "group10",
    "group241",
    "rectangle30",
    "group242"
  ],

  group243: [
    "group243",
    "_2Geda11",
    "group10",
    "group241",
    "rectangle30",
    "group242"
  ],

  _2Geda11: ["_2Geda11"],
  group10: ["group10", "group241", "rectangle30"],
  group241: ["group241", "rectangle30"],
  rectangle30: ["rectangle30"],
  group242: ["group242"],
  content: [
    "content",
    "freeBox",
    "outletTop",
    "group289",
    "rectangle296",
    "rectangle218",
    "group161",
    "group160",
    "rectangle216",
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268",
    "rectangle214",
    "group164",
    "group165",
    "rectangle219",
    "widget",
    "categoriesBox",
    "categoriesGrid",
    "group116",
    "inventoryList",
    "list",
    "group166",
    "redNike"
  ],

  freeBox: [
    "freeBox",
    "outletTop",
    "group289",
    "rectangle296",
    "rectangle218",
    "group161",
    "group160",
    "rectangle216",
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268",
    "rectangle214",
    "group164",
    "group165",
    "rectangle219"
  ],

  outletTop: ["outletTop", "group289", "rectangle296"],
  group289: ["group289", "rectangle296"],
  rectangle296: ["rectangle296"],
  rectangle218: ["rectangle218", "group161", "group160", "rectangle216"],
  group161: ["group161", "group160", "rectangle216"],
  group160: ["group160", "rectangle216"],
  rectangle216: ["rectangle216"],
  rectangle213: [
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268"
  ],

  group162: [
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268"
  ],

  group230: [
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268"
  ],

  rectangle264: ["rectangle264"],
  group286: ["group286", "group224"],
  group224: ["group224"],
  group225: ["group225", "rectangle268"],
  rectangle268: ["rectangle268"],
  rectangle214: ["rectangle214", "group164", "group165", "rectangle219"],
  group164: ["group164", "group165", "rectangle219"],
  group165: ["group165", "rectangle219"],
  rectangle219: ["rectangle219"],
  widget: [
    "widget",
    "categoriesBox",
    "categoriesGrid",
    "group116",
    "inventoryList",
    "list",
    "group166",
    "redNike"
  ],

  categoriesBox: ["categoriesBox", "categoriesGrid", "group116"],
  categoriesGrid: ["categoriesGrid", "group116"],
  group116: ["group116"],
  inventoryList: ["inventoryList", "list", "group166", "redNike"],
  list: ["list", "group166", "redNike"],
  group166: ["group166", "redNike"],
  redNike: ["redNike"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBusiness__ArgProps,
          internalVariantPropNames: PlasmicBusiness__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicBusiness__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "business") {
    func.displayName = "PlasmicBusiness";
  } else {
    func.displayName = `PlasmicBusiness.${nodeName}`;
  }
  return func;
}

export const PlasmicBusiness = Object.assign(
  // Top-level PlasmicBusiness renders the root element
  makeNodeComponent("business"),
  {
    // Helper components rendering sub-elements
    sidebar: makeNodeComponent("sidebar"),
    group246: makeNodeComponent("group246"),
    group214: makeNodeComponent("group214"),
    group244: makeNodeComponent("group244"),
    group140: makeNodeComponent("group140"),
    home: makeNodeComponent("home"),
    marketplace: makeNodeComponent("marketplace"),
    profile: makeNodeComponent("profile"),
    messages: makeNodeComponent("messages"),
    messages2: makeNodeComponent("messages2"),
    nofitication: makeNodeComponent("nofitication"),
    group245: makeNodeComponent("group245"),
    main: makeNodeComponent("main"),
    header: makeNodeComponent("header"),
    group243: makeNodeComponent("group243"),
    _2Geda11: makeNodeComponent("_2Geda11"),
    group10: makeNodeComponent("group10"),
    group241: makeNodeComponent("group241"),
    rectangle30: makeNodeComponent("rectangle30"),
    group242: makeNodeComponent("group242"),
    content: makeNodeComponent("content"),
    freeBox: makeNodeComponent("freeBox"),
    outletTop: makeNodeComponent("outletTop"),
    group289: makeNodeComponent("group289"),
    rectangle296: makeNodeComponent("rectangle296"),
    rectangle218: makeNodeComponent("rectangle218"),
    group161: makeNodeComponent("group161"),
    group160: makeNodeComponent("group160"),
    rectangle216: makeNodeComponent("rectangle216"),
    rectangle213: makeNodeComponent("rectangle213"),
    group162: makeNodeComponent("group162"),
    group230: makeNodeComponent("group230"),
    rectangle264: makeNodeComponent("rectangle264"),
    group286: makeNodeComponent("group286"),
    group224: makeNodeComponent("group224"),
    group225: makeNodeComponent("group225"),
    rectangle268: makeNodeComponent("rectangle268"),
    rectangle214: makeNodeComponent("rectangle214"),
    group164: makeNodeComponent("group164"),
    group165: makeNodeComponent("group165"),
    rectangle219: makeNodeComponent("rectangle219"),
    widget: makeNodeComponent("widget"),
    categoriesBox: makeNodeComponent("categoriesBox"),
    categoriesGrid: makeNodeComponent("categoriesGrid"),
    group116: makeNodeComponent("group116"),
    inventoryList: makeNodeComponent("inventoryList"),
    list: makeNodeComponent("list"),
    group166: makeNodeComponent("group166"),
    redNike: makeNodeComponent("redNike"),
    // Metadata about props expected for PlasmicBusiness
    internalVariantProps: PlasmicBusiness__VariantProps,
    internalArgProps: PlasmicBusiness__ArgProps
  }
);

export default PlasmicBusiness;
/* prettier-ignore-end */
