// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ovjdXhydzXTq3Bc7u9wCpt
// Component: 0r3xSegb8up
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsgcBBykOvh4Vq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gcB_bykOvh4VQ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_2_geda.module.css"; // plasmic-import: ovjdXhydzXTq3Bc7u9wCpt/projectcss
import sty from "./PlasmicBusinessSidebar.module.css"; // plasmic-import: 0r3xSegb8up/css
import HouseIcon from "./icons/PlasmicIcon__House"; // plasmic-import: IdSuw-EtCN/icon
import UserCircleIcon from "./icons/PlasmicIcon__UserCircle"; // plasmic-import: EP5zGWwJ1X/icon
import Vector96Icon from "./icons/PlasmicIcon__Vector96"; // plasmic-import: 9n_rLIVux/icon
import Vector97Icon from "./icons/PlasmicIcon__Vector97"; // plasmic-import: Rb7mIprIrQ/icon
import BellIcon from "./icons/PlasmicIcon__Bell"; // plasmic-import: grfZD_Hnz9/icon
import SignOutIcon from "./icons/PlasmicIcon__SignOut"; // plasmic-import: PV-wOd8DPw/icon
import storefrontXeuODvyCe from "./images/storefront.svg"; // plasmic-import: xeuODvy_ce/picture

export const PlasmicBusinessSidebar__VariantProps = new Array();

export const PlasmicBusinessSidebar__ArgProps = new Array();

function PlasmicBusinessSidebar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgcBBykOvh4Vq()
  });

  return (hasVariant(globalVariants, "screen", "tablet") ? true : true) ? (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"group140"}
        data-plasmic-override={overrides.group140}
        hasGap={true}
        className={classNames(projectcss.all, sty.group140)}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"home"}
          data-plasmic-override={overrides.home}
          hasGap={true}
          className={classNames(projectcss.all, sty.home)}
        >
          <HouseIcon
            className={classNames(projectcss.all, sty.svg__wzJTj)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__hK09V
            )}
          >
            {"Home"}
          </div>
        </p.Stack>

        <div
          data-plasmic-name={"marketplace"}
          data-plasmic-override={overrides.marketplace}
          className={classNames(projectcss.all, sty.marketplace)}
        >
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"32px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: storefrontXeuODvyCe,
              fullWidth: 32,
              fullHeight: 32,
              aspectRatio: 1
            }}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vN84G
            )}
          >
            {"Business"}
          </div>
        </div>

        <p.Stack
          as={"div"}
          data-plasmic-name={"profile"}
          data-plasmic-override={overrides.profile}
          hasGap={true}
          className={classNames(projectcss.all, sty.profile)}
        >
          <UserCircleIcon
            className={classNames(projectcss.all, sty.svg__aYSug)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__n5Bo
            )}
          >
            {"People"}
          </div>
        </p.Stack>

        <div
          data-plasmic-name={"messages"}
          data-plasmic-override={overrides.messages}
          className={classNames(projectcss.all, sty.messages)}
        >
          <div
            data-plasmic-name={"messages2"}
            data-plasmic-override={overrides.messages2}
            className={classNames(projectcss.all, sty.messages2)}
          >
            <Vector96Icon
              className={classNames(projectcss.all, sty.svg__w4TUp)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___70HTj
              )}
            >
              {"Messages"}
            </div>
          </div>

          <Vector97Icon
            className={classNames(projectcss.all, sty.svg__tbfBo)}
            role={"img"}
          />

          <Vector97Icon
            className={classNames(projectcss.all, sty.svg__ugC96)}
            role={"img"}
          />

          <Vector97Icon
            className={classNames(projectcss.all, sty.svg__rsQnm)}
            role={"img"}
          />
        </div>

        <div
          data-plasmic-name={"nofitication"}
          data-plasmic-override={overrides.nofitication}
          className={classNames(projectcss.all, sty.nofitication)}
        >
          <BellIcon
            className={classNames(projectcss.all, sty.svg__xrIau)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__yqXn
            )}
          >
            {"Notification"}
          </div>
        </div>
      </p.Stack>

      <p.Stack
        as={"div"}
        data-plasmic-name={"group245"}
        data-plasmic-override={overrides.group245}
        hasGap={true}
        className={classNames(projectcss.all, sty.group245)}
      >
        <SignOutIcon
          className={classNames(projectcss.all, sty.svg__kt3LX)}
          role={"img"}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ewEYo
          )}
        >
          {"Sign out"}
        </div>
      </p.Stack>
    </div>
  ) : null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "group140",
    "home",
    "marketplace",
    "img",
    "profile",
    "messages",
    "messages2",
    "nofitication",
    "group245"
  ],

  group140: [
    "group140",
    "home",
    "marketplace",
    "img",
    "profile",
    "messages",
    "messages2",
    "nofitication"
  ],

  home: ["home"],
  marketplace: ["marketplace", "img"],
  img: ["img"],
  profile: ["profile"],
  messages: ["messages", "messages2"],
  messages2: ["messages2"],
  nofitication: ["nofitication"],
  group245: ["group245"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBusinessSidebar__ArgProps,
          internalVariantPropNames: PlasmicBusinessSidebar__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicBusinessSidebar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBusinessSidebar";
  } else {
    func.displayName = `PlasmicBusinessSidebar.${nodeName}`;
  }
  return func;
}

export const PlasmicBusinessSidebar = Object.assign(
  // Top-level PlasmicBusinessSidebar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    group140: makeNodeComponent("group140"),
    home: makeNodeComponent("home"),
    marketplace: makeNodeComponent("marketplace"),
    img: makeNodeComponent("img"),
    profile: makeNodeComponent("profile"),
    messages: makeNodeComponent("messages"),
    messages2: makeNodeComponent("messages2"),
    nofitication: makeNodeComponent("nofitication"),
    group245: makeNodeComponent("group245"),
    // Metadata about props expected for PlasmicBusinessSidebar
    internalVariantProps: PlasmicBusinessSidebar__VariantProps,
    internalArgProps: PlasmicBusinessSidebar__ArgProps
  }
);

export default PlasmicBusinessSidebar;
/* prettier-ignore-end */
