// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ovjdXhydzXTq3Bc7u9wCpt
// Component: fWa5Q_WBlB
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import ModalLeft from "../../ModalLeft"; // plasmic-import: DFjZBtsg3Y/component
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicForgotPasswordModalLeft.module.css"; // plasmic-import: fWa5Q_WBlB/css

export const PlasmicForgotPasswordModalLeft__VariantProps = new Array();

export const PlasmicForgotPasswordModalLeft__ArgProps = new Array();

function PlasmicForgotPasswordModalLeft__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  return (
    <ModalLeft
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicForgotPasswordModalLeft__ArgProps,
          internalVariantPropNames: PlasmicForgotPasswordModalLeft__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicForgotPasswordModalLeft__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicForgotPasswordModalLeft";
  } else {
    func.displayName = `PlasmicForgotPasswordModalLeft.${nodeName}`;
  }
  return func;
}

export const PlasmicForgotPasswordModalLeft = Object.assign(
  // Top-level PlasmicForgotPasswordModalLeft renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicForgotPasswordModalLeft
    internalVariantProps: PlasmicForgotPasswordModalLeft__VariantProps,
    internalArgProps: PlasmicForgotPasswordModalLeft__ArgProps
  }
);

export default PlasmicForgotPasswordModalLeft;
/* prettier-ignore-end */
