// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ovjdXhydzXTq3Bc7u9wCpt
// Component: 05xKepNiDk
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import BusinessSidebar2 from "../../BusinessSidebar2"; // plasmic-import: q5yCu6U9uj/component
import BusinessHeader from "../../BusinessHeader"; // plasmic-import: QNsWw2e-3G/component
import SelectCategory from "../../SelectCategory"; // plasmic-import: 6HSr9YyfAE/component
import InventoryList from "../../InventoryList"; // plasmic-import: Gn6XkLaEoG/component
import { useScreenVariants as useScreenVariantsgcBBykOvh4Vq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gcB_bykOvh4VQ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_2_geda.module.css"; // plasmic-import: ovjdXhydzXTq3Bc7u9wCpt/projectcss
import sty from "./PlasmicBusiness.module.css"; // plasmic-import: 05xKepNiDk/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: sFbk0B4_vB/icon
import Star2Icon from "./icons/PlasmicIcon__Star2"; // plasmic-import: w5JllfIkrJ/icon
import Star3Icon from "./icons/PlasmicIcon__Star3"; // plasmic-import: Yl4IrwGzJU/icon
import Star4Icon from "./icons/PlasmicIcon__Star4"; // plasmic-import: XQCQaCpB-/icon
import Star5Icon from "./icons/PlasmicIcon__Star5"; // plasmic-import: 287U2hOue7/icon
import unsplashINwSiOcNzMgEGqqCl3UoC2 from "./images/unsplashINwSiOcNzMg.jpeg"; // plasmic-import: EGqqCl3UoC2/picture

export const PlasmicBusiness__VariantProps = new Array();

export const PlasmicBusiness__ArgProps = new Array();

function PlasmicBusiness__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgcBBykOvh4Vq()
  });

  return (
    <React.Fragment>
      <div
        data-plasmic-name={"business"}
        data-plasmic-override={overrides.business}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.business
        )}
      >
        {(hasVariant(globalVariants, "screen", "tablet") ? true : true) ? (
          <BusinessSidebar2
            data-plasmic-name={"businessSidebar2"}
            data-plasmic-override={overrides.businessSidebar2}
            className={classNames("__wab_instance", sty.businessSidebar2)}
          />
        ) : null}

        <div
          data-plasmic-name={"main"}
          data-plasmic-override={overrides.main}
          className={classNames(projectcss.all, sty.main)}
        >
          <BusinessHeader
            data-plasmic-name={"businessHeader"}
            data-plasmic-override={overrides.businessHeader}
            className={classNames("__wab_instance", sty.businessHeader)}
          />

          <div
            data-plasmic-name={"content"}
            data-plasmic-override={overrides.content}
            className={classNames(projectcss.all, sty.content)}
          >
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <div
                data-plasmic-name={"outletTop"}
                data-plasmic-override={overrides.outletTop}
                className={classNames(projectcss.all, sty.outletTop)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__klm3R
                  )}
                >
                  {"Buy and sell instantly"}
                </div>

                <div
                  data-plasmic-name={"group289"}
                  data-plasmic-override={overrides.group289}
                  className={classNames(projectcss.all, sty.group289)}
                >
                  <button
                    data-plasmic-name={"rectangle296"}
                    data-plasmic-override={overrides.rectangle296}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      sty.rectangle296
                    )}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__geHup
                    )}
                  >
                    {"Manage Businesess"}
                  </div>
                </div>
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"rectangle218"}
                data-plasmic-override={overrides.rectangle218}
                hasGap={true}
                className={classNames(projectcss.all, sty.rectangle218)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iGiig
                  )}
                >
                  {"Trending and Hot"}
                </div>

                <div
                  data-plasmic-name={"group161"}
                  data-plasmic-override={overrides.group161}
                  className={classNames(projectcss.all, sty.group161)}
                >
                  {true ? (
                    <div
                      data-plasmic-name={"group160"}
                      data-plasmic-override={overrides.group160}
                      className={classNames(projectcss.all, sty.group160)}
                    >
                      <div
                        data-plasmic-name={"rectangle216"}
                        data-plasmic-override={overrides.rectangle216}
                        className={classNames(projectcss.all, sty.rectangle216)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__t687R)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: unsplashINwSiOcNzMgEGqqCl3UoC2,
                            fullWidth: 2880,
                            fullHeight: 1620,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__trRYs
                        )}
                      >
                        {"Semi detached duplex"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aFgPq
                        )}
                      >
                        {"#200,000"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a9Vd9
                        )}
                      >
                        {"Lekki, Lagos"}
                      </div>
                    </div>
                  ) : null}
                </div>
              </p.Stack>

              <div
                data-plasmic-name={"rectangle213"}
                data-plasmic-override={overrides.rectangle213}
                className={classNames(projectcss.all, sty.rectangle213)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cRdrn
                  )}
                >
                  {"Suggested Businesses"}
                </div>

                <div
                  data-plasmic-name={"group162"}
                  data-plasmic-override={overrides.group162}
                  className={classNames(projectcss.all, sty.group162)}
                >
                  <div
                    data-plasmic-name={"group230"}
                    data-plasmic-override={overrides.group230}
                    className={classNames(projectcss.all, sty.group230)}
                  >
                    <div
                      data-plasmic-name={"rectangle264"}
                      data-plasmic-override={overrides.rectangle264}
                      className={classNames(projectcss.all, sty.rectangle264)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___0FitV)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: unsplashINwSiOcNzMgEGqqCl3UoC2,
                          fullWidth: 2880,
                          fullHeight: 1620,
                          aspectRatio: undefined
                        }}
                      />
                    </div>

                    <div
                      data-plasmic-name={"group286"}
                      data-plasmic-override={overrides.group286}
                      className={classNames(projectcss.all, sty.group286)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mkeef
                        )}
                      >
                        {"Business Page 1"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uu46
                        )}
                      >
                        {"Lagos | Nigeria"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__c9Wek
                        )}
                      >
                        {"Estd. 2011"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yMpjc
                        )}
                      >
                        {"Average rating : 4.5"}
                      </div>

                      <div
                        data-plasmic-name={"group224"}
                        data-plasmic-override={overrides.group224}
                        className={classNames(projectcss.all, sty.group224)}
                      >
                        <StarIcon
                          className={classNames(projectcss.all, sty.svg__qK0KP)}
                          role={"img"}
                        />

                        <Star2Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___2B220
                          )}
                          role={"img"}
                        />

                        <Star3Icon
                          className={classNames(projectcss.all, sty.svg__pszMx)}
                          role={"img"}
                        />

                        <Star4Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3Dg7D
                          )}
                          role={"img"}
                        />

                        <Star5Icon
                          className={classNames(projectcss.all, sty.svg__bGy96)}
                          role={"img"}
                        />
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"group225"}
                      data-plasmic-override={overrides.group225}
                      className={classNames(projectcss.all, sty.group225)}
                    >
                      <button
                        data-plasmic-name={"rectangle268"}
                        data-plasmic-override={overrides.rectangle268}
                        className={classNames(
                          projectcss.all,
                          projectcss.button,
                          sty.rectangle268
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iuPi2
                        )}
                      >
                        {"Follow"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle214"}
                data-plasmic-override={overrides.rectangle214}
                className={classNames(projectcss.all, sty.rectangle214)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6PDlT
                  )}
                >
                  {"Automobile"}
                </div>

                <div
                  data-plasmic-name={"group164"}
                  data-plasmic-override={overrides.group164}
                  className={classNames(projectcss.all, sty.group164)}
                >
                  {true ? (
                    <div
                      data-plasmic-name={"group165"}
                      data-plasmic-override={overrides.group165}
                      className={classNames(projectcss.all, sty.group165)}
                    >
                      <div
                        data-plasmic-name={"rectangle219"}
                        data-plasmic-override={overrides.rectangle219}
                        className={classNames(projectcss.all, sty.rectangle219)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ri9Vw)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: unsplashINwSiOcNzMgEGqqCl3UoC2,
                            fullWidth: 2880,
                            fullHeight: 1620,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nUMe7
                        )}
                      >
                        {"Semi detached duplex"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jEfa0
                        )}
                      >
                        {"#200,000"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lI5J6
                        )}
                      >
                        {"Lekki, Lagos"}
                      </div>
                    </div>
                  ) : null}
                </div>
              </div>
            </div>

            {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
              <div
                data-plasmic-name={"widget"}
                data-plasmic-override={overrides.widget}
                className={classNames(projectcss.all, sty.widget)}
              >
                <SelectCategory
                  data-plasmic-name={"selectCategory"}
                  data-plasmic-override={overrides.selectCategory}
                  className={classNames("__wab_instance", sty.selectCategory)}
                />

                <InventoryList
                  data-plasmic-name={"inventoryList"}
                  data-plasmic-override={overrides.inventoryList}
                  className={classNames("__wab_instance", sty.inventoryList)}
                />
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  business: [
    "business",
    "businessSidebar2",
    "main",
    "businessHeader",
    "content",
    "freeBox",
    "outletTop",
    "group289",
    "rectangle296",
    "rectangle218",
    "group161",
    "group160",
    "rectangle216",
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268",
    "rectangle214",
    "group164",
    "group165",
    "rectangle219",
    "widget",
    "selectCategory",
    "inventoryList"
  ],

  businessSidebar2: ["businessSidebar2"],
  main: [
    "main",
    "businessHeader",
    "content",
    "freeBox",
    "outletTop",
    "group289",
    "rectangle296",
    "rectangle218",
    "group161",
    "group160",
    "rectangle216",
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268",
    "rectangle214",
    "group164",
    "group165",
    "rectangle219",
    "widget",
    "selectCategory",
    "inventoryList"
  ],

  businessHeader: ["businessHeader"],
  content: [
    "content",
    "freeBox",
    "outletTop",
    "group289",
    "rectangle296",
    "rectangle218",
    "group161",
    "group160",
    "rectangle216",
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268",
    "rectangle214",
    "group164",
    "group165",
    "rectangle219",
    "widget",
    "selectCategory",
    "inventoryList"
  ],

  freeBox: [
    "freeBox",
    "outletTop",
    "group289",
    "rectangle296",
    "rectangle218",
    "group161",
    "group160",
    "rectangle216",
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268",
    "rectangle214",
    "group164",
    "group165",
    "rectangle219"
  ],

  outletTop: ["outletTop", "group289", "rectangle296"],
  group289: ["group289", "rectangle296"],
  rectangle296: ["rectangle296"],
  rectangle218: ["rectangle218", "group161", "group160", "rectangle216"],
  group161: ["group161", "group160", "rectangle216"],
  group160: ["group160", "rectangle216"],
  rectangle216: ["rectangle216"],
  rectangle213: [
    "rectangle213",
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268"
  ],

  group162: [
    "group162",
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268"
  ],

  group230: [
    "group230",
    "rectangle264",
    "group286",
    "group224",
    "group225",
    "rectangle268"
  ],

  rectangle264: ["rectangle264"],
  group286: ["group286", "group224"],
  group224: ["group224"],
  group225: ["group225", "rectangle268"],
  rectangle268: ["rectangle268"],
  rectangle214: ["rectangle214", "group164", "group165", "rectangle219"],
  group164: ["group164", "group165", "rectangle219"],
  group165: ["group165", "rectangle219"],
  rectangle219: ["rectangle219"],
  widget: ["widget", "selectCategory", "inventoryList"],
  selectCategory: ["selectCategory"],
  inventoryList: ["inventoryList"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBusiness__ArgProps,
          internalVariantPropNames: PlasmicBusiness__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicBusiness__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "business") {
    func.displayName = "PlasmicBusiness";
  } else {
    func.displayName = `PlasmicBusiness.${nodeName}`;
  }
  return func;
}

export const PlasmicBusiness = Object.assign(
  // Top-level PlasmicBusiness renders the root element
  makeNodeComponent("business"),
  {
    // Helper components rendering sub-elements
    businessSidebar2: makeNodeComponent("businessSidebar2"),
    main: makeNodeComponent("main"),
    businessHeader: makeNodeComponent("businessHeader"),
    content: makeNodeComponent("content"),
    freeBox: makeNodeComponent("freeBox"),
    outletTop: makeNodeComponent("outletTop"),
    group289: makeNodeComponent("group289"),
    rectangle296: makeNodeComponent("rectangle296"),
    rectangle218: makeNodeComponent("rectangle218"),
    group161: makeNodeComponent("group161"),
    group160: makeNodeComponent("group160"),
    rectangle216: makeNodeComponent("rectangle216"),
    rectangle213: makeNodeComponent("rectangle213"),
    group162: makeNodeComponent("group162"),
    group230: makeNodeComponent("group230"),
    rectangle264: makeNodeComponent("rectangle264"),
    group286: makeNodeComponent("group286"),
    group224: makeNodeComponent("group224"),
    group225: makeNodeComponent("group225"),
    rectangle268: makeNodeComponent("rectangle268"),
    rectangle214: makeNodeComponent("rectangle214"),
    group164: makeNodeComponent("group164"),
    group165: makeNodeComponent("group165"),
    rectangle219: makeNodeComponent("rectangle219"),
    widget: makeNodeComponent("widget"),
    selectCategory: makeNodeComponent("selectCategory"),
    inventoryList: makeNodeComponent("inventoryList"),
    // Metadata about props expected for PlasmicBusiness
    internalVariantProps: PlasmicBusiness__VariantProps,
    internalArgProps: PlasmicBusiness__ArgProps
  }
);

export default PlasmicBusiness;
/* prettier-ignore-end */
